#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'application_ruby'
cookbook 'apt'
cookbook 'user'
cookbook 'ruby_build'
cookbook 'redisio'
cookbook 'postgresql'
cookbook 'ssh_known_hosts'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
